title: "Elvee Project"
author: ""
description: ""
permalink: /:title/
lang: "en"
excerpt_separator: "\n\n\n"
date_format: "%B %d, %Y"

# Layout

show_excerpts: false        # show article excerpts on the home page
show_frame: true           # adds a gray frame to the site
show_sidebar: true        # show a sidebar instead of the usual header
minimal: false             # use a dark header

# Menu

navigation:                # accepts {file, title, url, icon, sidebaricon}
  - {title: "The Elvee Project",file: "index.md",  icon: home, sidebaricon: home}
   - {title: "Explanation of the system",file: "explanation of the system.md",  icon: briefcase, sidebaricon: briefcase}
  - {title: "Elvee Light", file: "elvee_light.md",  icon: briefcase, sidebaricon: briefcase}
  - {title: "Elvee Pulse", file: "elvee_pulse.md",  icon: briefcase, sidebaricon: briefcase} 
  - {title: "Elvee Education", file: "elvee_education.md",  icon: briefcase, sidebaricon: briefcase} 
  - {title: "Create your own Elvee Pulse!", file: "create_your_own.md",  icon: briefcase, sidebaricon: briefcase}  
  - {title: "Hardware", file: "hardware.md",  icon: briefcase, sidebaricon: briefcase} 
  - {title: "Firmware", file: "firmware.md",  icon: briefcase, sidebaricon: briefcase} 
  - {title: "3D case", file: "3D_case.md",  icon: briefcase, sidebaricon: briefcase} 
  - {title: "Printed Board", file: "printed_board.md",  icon: briefcase, sidebaricon: briefcase} 

external:                  # shows a footer with social links - for available icons see fontawesome.com/icons
  - {title: Github, icon: github, url: "https://github.com/ElveePulse"}
  - {title: Linkedin, icon: linkedin, url: ""}
  - {title: Mail, icon: envelope, url: ""}
comments:
#  disqus_shortname: ""    # see https://disqus.com/
#  isso_domain: ""         # see https://posativ.org/isso/

plugins:
 - jekyll-feed
